apiVersion: v1
kind: Service
metadata:
  name: {{ include "aisensebot-enterprise.fullname" . }}-backend
  labels:
    {{- include "aisensebot-enterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.backend.type }}
  ports:
    - port: {{ .Values.services.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
