# Rasa NLU config file
# This defines the NLU pipeline and policies for your Rasa assistant.

# Language
language: zh

# NLU Pipeline
# This pipeline is a good starting point for a simple NLU bot in Chinese.
pipeline:
  - name: WhitespaceTokenizer
  - name: JiebaTokenizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-chinese"
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Policies for dialogue management
# These policies decide the next action of the bot.
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
